


def test():
    print("Test Function")

def print_head_Info(file):
    file.write("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n")

def print_scene_head(file):
    file.write("<scene version=\"0.5.0\">\n")

def print_scene_tail(file):
    file.write("</scene>\n")

def integrator(file):
    file.write("	<integrator type=\"bdpt\">\n")
    file.write("		<integer name=\"maxDepth\" value=\"20\"/>\n")
    file.write("	</integrator>\n")

def perspective(file):
    file.write("	<sensor type=\"perspective\">\n")
    file.write("		<float name=\"farClip\" value=\"100\"/>\n")
    file.write("		<float name=\"focusDistance\" value=\"7\"/>\n")
    file.write("		<float name=\"fov\" value=\"44.5513\"/>\n")
    file.write("		<string name=\"fovAxis\" value=\"x\"/>\n")
    file.write("		<float name=\"nearClip\" value=\"0.1\"/>\n")
    file.write("		<transform name=\"toWorld\">\n")
    file.write("			<lookat target=\"-0.261616, 5.64477, 0.309317\" origin=\"-0.223944, 120.64245, 0.366128\" up=\"0, 0, 1\"/>\n")
    file.write("		</transform>\n")
    file.write("		<sampler type=\"ldsampler\">\n")
    file.write("			<integer name=\"sampleCount\" value=\"64\"/>\n")
    file.write("		</sampler>\n")
    file.write("		<film type=\"hdrfilm\">\n")
    file.write("			<integer name=\"height\" value=\"720\"/>\n")
    file.write("			<integer name=\"width\" value=\"1280\"/>\n")
    file.write("		</film>\n")
    file.write("	</sensor>\n")

def bsdf_water_drop(file):
    file.write("	<bsdf type=\"dielectric\" id=\"Water_Drop\">\n")
    file.write("		<float name=\"extIOR\" value=\"1.00028\"/>\n")
    file.write("		<float name=\"intIOR\" value=\"1.333\"/>\n")
    file.write("	</bsdf>\n")

def envmap(file):
    file.write("	<emitter type=\"envmap\">\n")
    file.write("		<string name=\"filename\" value=\"sky.hdr\"/>\n")
    file.write("		<transform name=\"toWorld\">\n")
    file.write("			<rotate x=\"1\" angle=\"120\"/>\n")
    file.write("			<rotate z=\"1\" angle=\"75\"/>\n")
    file.write("			<rotate y=\"1\" angle=\"-30\"/>\n")
    file.write("		</transform>\n")
    file.write("	</emitter>\n")

def glass(file):
    file.write("	<shape type=\"serialized\" id=\"Glass_Final\">\n")
    file.write("		<string name=\"filename\" value=\"bidir.serialized\"/>\n")
    file.write("		<integer name=\"shapeIndex\" value=\"10\"/>\n")
    file.write("		<transform name=\"toWorld\">\n")
    file.write("			<rotate x=\"0\" y=\"0\" z=\"1\" angle=\"90\"/>\n")
    file.write("			<rotate x=\"1\" y=\"0\" z=\"0\" angle=\"90\"/>\n")
    file.write("			<rotate x=\"0\" y=\"1\" z=\"0\" angle=\"90\"/>\n")
    file.write("			<translate x=\"0\" y=\"0\" z=\"-0.02\"/>\n")
    file.write("			<scale x=\"20\" y=\"0.02\" z=\"60\"/>\n")
    file.write("		</transform>\n")
    file.write("		<bsdf type=\"roughdielectric\">\n")
    file.write("			<string name=\"distribution\" value=\"beckmann\"/>\n")
    file.write("			<float name=\"alpha\" value=\"0.05\"/> \n")
    file.write("			<float name=\"intIOR\" value=\"1.50\"/> \n")
    file.write("			<float name=\"extIOR\" value=\"1.00028\"/>\n")
    file.write("		</bsdf>\n")
    file.write("		<medium type=\"homogeneous\" name=\"interior\">\n")
    file.write("			<rgb name=\"sigmaS\" value=\"0, 0, 0\"/>\n")
    file.write("			<rgb name=\"sigmaA\" value=\"4, 4, 2\"/>\n")
    file.write("		</medium>\n")
    file.write("	</shape>\n")

def test_obj(file):
    file.write("	<shape type=\"sphere\">\n")
    file.write("		<ref id=\"Water_Drop\"/>\n")
    file.write("		<transform name=\"toWorld\">\n")
    file.write("			<scale x=\"1\" y=\"1\" z=\"1\"/>\n")
    file.write("		</transform>\n")
    file.write("	</shape>\n")
    file.write("	<shape type=\"obj\">\n")
    file.write("		<string name=\"filename\" value=\"dynamic_drop_11n.obj\"/>\n")
    file.write("		<transform name=\"toWorld\">\n")
    file.write("			<translate x=\"10\" y=\"30\" z=\"0\"/>\n")
    file.write("			<rotate x=\"0\" y=\"0\" z=\"1\" angle=\"-90\"/>\n")
    file.write("			<rotate x=\"1\" y=\"0\" z=\"0\" angle=\"-90\"/>\n")
    file.write("			<rotate x=\"0\" y=\"1\" z=\"0\" angle=\"90\"/>\n")
    file.write("		</transform>\n")
    file.write("		<ref id=\"Water_Drop\"/>\n")
    file.write("	</shape>\n")

    file.write("	<shape type=\"obj\">\n")
    file.write("		<string name=\"filename\" value=\"dynamic_drop_6n.obj\"/>\n")
    file.write("		<transform name=\"toWorld\">\n")
    file.write("			<translate x=\"10\" y=\"0\" z=\"0\"/>\n")
    file.write("			<rotate x=\"0\" y=\"0\" z=\"1\" angle=\"-90\"/>\n")
    file.write("			<rotate x=\"1\" y=\"0\" z=\"0\" angle=\"90\"/>\n")
    file.write("			<rotate x=\"0\" y=\"1\" z=\"0\" angle=\"90\"/>\n")
    file.write("		</transform>\n")
    file.write("		<ref id=\"Water_Drop\"/>\n")
    file.write("	</shape>\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")
    file.write("\n")



